### PR TITLE
Fix authentication error

### LINKED ISSUE #112: Login is incorrect, please fix log in settings
Game updated a few mins ago, a few dependencies were installed, and ever since then the app seems broken! Any updates?

### LINKED ISSUE #114: Login is incorrect
Login is incorrect, please fix login in settings "but my user name and password is correct"

image

### PR DESCRIPTION
**Pull request by Jaren8r**
Fixes #112, Fixes #114

### CODE REVIEW

**Review by drobnyy — APPROVED** [review]

**Comment by drobnyy** [comment]
I tested this with Postman and it works.

**Comment by shakeabi** [comment]
@drobnyy Can you check again, the "opt-in" in the end shouldn't be there, it throws an error. #116 works fine

**Comment by drobnyy** [comment]
it works for me with Postman

**Comment by shakeabi** [comment]
Tested with postman as well.

Payload: {"client_id":"play-valorant-web-prod","nonce":"1","redirect_uri":"https://playvalorant.com/opt-in","response_type":"token id_token","scope":"account openid"}

Response: {
    "type": "error",
    "error": "invalid_request",
    "error_description": "The \"redirect_uri\" for client play-valorant-web-prod is not registered: https://playvalorant.com/opt-in",
    "country": "ind"
}

**Comment by drobnyy** [comment]
You got bad parameter "redirect_uri". 
Check this:
 "redirect_uri": "https://playvalorant.com/opt_in"
, not 
"redirect_uri":"https://playvalorant.com/opt-in"

**Comment by andrecadete** [comment]
Ah damn @Jaren8r you were 4 minutes faster 😂 

@shakeabi is that not because you're calling `/opt-in` and not `/opt_in` ?

Anyway if that path is unecessary I'd suggest removing it. anyway #116 is there if you want to merge it @RumbleMike otherwise merge this one and close mine!

**Comment by shakeabi** [comment]
Aaah my bad, Sry for the confusion

**Comment by andrecadete** [comment]
If it is unnecessary I suggest @RumbleMike could remove it. Sooner or later it might stop working with the path included too since that URL was obviously a BETA opt-in page which no longer exists or is needed whatsoever.

**Comment by tomsouris** [comment]
I build one version with the new URI, everything works fine.
GoodJob boys, and thx Mike for the tool.

**Pull request merged**
